Exception 5 thrown!
5

==========
Statistics
==========

Objects created:
   Exception |-> 1
   Main |-> 1

Methods invoked:
   Exception.Exception |-> 1
   Exception.get |-> 1
   Main.Main |-> 1
   Main.foo |-> 1
